export const FOOD_DATABASE = [
    // Proteins
    { name: "Egg (1 large)", calories: 78, protein: 6, carbs: 1, fat: 5, sodium: 62, potassium: 63, category: "Protein" },
    { name: "Chicken Breast (100g)", calories: 165, protein: 31, carbs: 0, fat: 3.6, sodium: 74, potassium: 256, category: "Protein" },
    { name: "Salmon (100g)", calories: 208, protein: 20, carbs: 0, fat: 13, sodium: 59, potassium: 363, category: "Protein" },
    { name: "Tuna (100g)", calories: 132, protein: 28, carbs: 0, fat: 1, sodium: 47, potassium: 252, category: "Protein" },
    { name: "Ground Beef (100g)", calories: 250, protein: 26, carbs: 0, fat: 15, sodium: 66, potassium: 305, category: "Protein" },
    { name: "Turkey Breast (100g)", calories: 135, protein: 30, carbs: 0, fat: 1, sodium: 50, potassium: 293, category: "Protein" },
    { name: "Shrimp (100g)", calories: 99, protein: 24, carbs: 0, fat: 0.3, sodium: 111, potassium: 259, category: "Protein" },
    { name: "Greek Yogurt (150g)", calories: 100, protein: 17, carbs: 6, fat: 1, sodium: 47, potassium: 220, category: "Protein" },
    { name: "Cottage Cheese (100g)", calories: 98, protein: 11, carbs: 3, fat: 4, sodium: 364, potassium: 104, category: "Protein" },
    { name: "Tofu (100g)", calories: 76, protein: 8, carbs: 2, fat: 5, sodium: 7, potassium: 121, category: "Protein" },
    { name: "Paneer (100g)", calories: 265, protein: 18, carbs: 1, fat: 20, sodium: 18, potassium: 100, category: "Protein" },
    { name: "Whey Protein Scoop", calories: 120, protein: 24, carbs: 3, fat: 1, sodium: 130, potassium: 160, category: "Protein" },
    // Grains & Carbs
    { name: "White Rice (100g cooked)", calories: 130, protein: 3, carbs: 28, fat: 0.3, sodium: 1, potassium: 35, category: "Grains" },
    { name: "Brown Rice (100g cooked)", calories: 123, protein: 3, carbs: 26, fat: 1, sodium: 1, potassium: 79, category: "Grains" },
    { name: "Oats (40g dry)", calories: 154, protein: 5, carbs: 27, fat: 3, sodium: 2, potassium: 147, category: "Grains" },
    { name: "Bread (1 slice)", calories: 79, protein: 3, carbs: 14, fat: 1, sodium: 147, potassium: 37, category: "Grains" },
    { name: "Whole Wheat Bread (1 slice)", calories: 81, protein: 4, carbs: 14, fat: 1, sodium: 146, potassium: 69, category: "Grains" },
    { name: "Pasta (100g cooked)", calories: 131, protein: 5, carbs: 25, fat: 1, sodium: 1, potassium: 44, category: "Grains" },
    { name: "Roti/Chapati (1 piece)", calories: 104, protein: 3, carbs: 18, fat: 3, sodium: 119, potassium: 69, category: "Grains" },
    { name: "Quinoa (100g cooked)", calories: 120, protein: 4, carbs: 21, fat: 2, sodium: 7, potassium: 172, category: "Grains" },
    { name: "Sweet Potato (100g)", calories: 86, protein: 2, carbs: 20, fat: 0, sodium: 55, potassium: 337, category: "Grains" },
    { name: "Potato (100g)", calories: 77, protein: 2, carbs: 17, fat: 0, sodium: 6, potassium: 421, category: "Grains" },
    // Fruits
    { name: "Banana (1 medium)", calories: 105, protein: 1, carbs: 27, fat: 0, sodium: 1, potassium: 422, category: "Fruits" },
    { name: "Apple (1 medium)", calories: 95, protein: 0, carbs: 25, fat: 0, sodium: 2, potassium: 195, category: "Fruits" },
    { name: "Orange (1 medium)", calories: 62, protein: 1, carbs: 15, fat: 0, sodium: 0, potassium: 237, category: "Fruits" },
    { name: "Blueberries (100g)", calories: 57, protein: 1, carbs: 14, fat: 0, sodium: 1, potassium: 77, category: "Fruits" },
    { name: "Strawberries (100g)", calories: 32, protein: 1, carbs: 8, fat: 0, sodium: 1, potassium: 153, category: "Fruits" },
    { name: "Mango (100g)", calories: 60, protein: 1, carbs: 15, fat: 0, sodium: 1, potassium: 168, category: "Fruits" },
    { name: "Grapes (100g)", calories: 69, protein: 1, carbs: 18, fat: 0, sodium: 2, potassium: 191, category: "Fruits" },
    { name: "Watermelon (100g)", calories: 30, protein: 1, carbs: 8, fat: 0, sodium: 1, potassium: 112, category: "Fruits" },
    { name: "Avocado (half)", calories: 160, protein: 2, carbs: 9, fat: 15, sodium: 7, potassium: 487, category: "Fruits" },
    // Vegetables
    { name: "Broccoli (100g)", calories: 34, protein: 3, carbs: 7, fat: 0, sodium: 33, potassium: 316, category: "Vegetables" },
    { name: "Spinach (100g)", calories: 23, protein: 3, carbs: 4, fat: 0, sodium: 79, potassium: 558, category: "Vegetables" },
    { name: "Tomato (1 medium)", calories: 22, protein: 1, carbs: 5, fat: 0, sodium: 6, potassium: 292, category: "Vegetables" },
    { name: "Cucumber (100g)", calories: 16, protein: 1, carbs: 4, fat: 0, sodium: 2, potassium: 147, category: "Vegetables" },
    { name: "Carrot (1 medium)", calories: 25, protein: 1, carbs: 6, fat: 0, sodium: 42, potassium: 195, category: "Vegetables" },
    { name: "Bell Pepper (1 medium)", calories: 31, protein: 1, carbs: 6, fat: 0, sodium: 4, potassium: 251, category: "Vegetables" },
    { name: "Onion (100g)", calories: 40, protein: 1, carbs: 9, fat: 0, sodium: 4, potassium: 146, category: "Vegetables" },
    { name: "Mushrooms (100g)", calories: 22, protein: 3, carbs: 3, fat: 0, sodium: 5, potassium: 318, category: "Vegetables" },
    // Dairy & Beverages
    { name: "Whole Milk (250ml)", calories: 150, protein: 8, carbs: 12, fat: 8, sodium: 105, potassium: 349, category: "Dairy" },
    { name: "Skim Milk (250ml)", calories: 83, protein: 8, carbs: 12, fat: 0, sodium: 127, potassium: 382, category: "Dairy" },
    { name: "Cheddar Cheese (30g)", calories: 120, protein: 7, carbs: 0, fat: 10, sodium: 176, potassium: 22, category: "Dairy" },
    { name: "Butter (1 tbsp)", calories: 102, protein: 0, carbs: 0, fat: 12, sodium: 82, potassium: 3, category: "Dairy" },
    // Nuts & Seeds
    { name: "Almonds (28g)", calories: 164, protein: 6, carbs: 6, fat: 14, sodium: 0, potassium: 200, category: "Nuts" },
    { name: "Peanuts (28g)", calories: 161, protein: 7, carbs: 5, fat: 14, sodium: 5, potassium: 200, category: "Nuts" },
    { name: "Walnuts (28g)", calories: 185, protein: 4, carbs: 4, fat: 18, sodium: 1, potassium: 125, category: "Nuts" },
    { name: "Peanut Butter (2 tbsp)", calories: 188, protein: 8, carbs: 6, fat: 16, sodium: 136, potassium: 208, category: "Nuts" },
    { name: "Chia Seeds (28g)", calories: 137, protein: 4, carbs: 12, fat: 9, sodium: 5, potassium: 115, category: "Nuts" },
    { name: "Flax Seeds (28g)", calories: 150, protein: 5, carbs: 8, fat: 12, sodium: 8, potassium: 228, category: "Nuts" },
    // Snacks & Others
    { name: "Protein Bar", calories: 200, protein: 20, carbs: 22, fat: 7, sodium: 200, potassium: 150, category: "Snacks" },
    { name: "Dark Chocolate (30g)", calories: 170, protein: 2, carbs: 13, fat: 12, sodium: 7, potassium: 200, category: "Snacks" },
    { name: "Honey (1 tbsp)", calories: 64, protein: 0, carbs: 17, fat: 0, sodium: 1, potassium: 11, category: "Snacks" },
    { name: "Olive Oil (1 tbsp)", calories: 119, protein: 0, carbs: 0, fat: 14, sodium: 0, potassium: 0, category: "Snacks" },
    { name: "Coffee (black)", calories: 2, protein: 0, carbs: 0, fat: 0, sodium: 5, potassium: 116, category: "Beverages" },
    { name: "Green Tea", calories: 0, protein: 0, carbs: 0, fat: 0, sodium: 1, potassium: 27, category: "Beverages" },
    { name: "Orange Juice (250ml)", calories: 112, protein: 2, carbs: 26, fat: 0, sodium: 2, potassium: 496, category: "Beverages" },
    { name: "Smoothie (banana+milk)", calories: 230, protein: 8, carbs: 40, fat: 4, sodium: 106, potassium: 771, category: "Beverages" },
    // Common Meals
    { name: "Caesar Salad", calories: 350, protein: 15, carbs: 20, fat: 22, sodium: 800, potassium: 350, category: "Meals" },
    { name: "Grilled Chicken Sandwich", calories: 420, protein: 32, carbs: 35, fat: 14, sodium: 780, potassium: 340, category: "Meals" },
    { name: "Veggie Burger", calories: 350, protein: 12, carbs: 40, fat: 15, sodium: 600, potassium: 400, category: "Meals" },
    { name: "Dal (1 bowl)", calories: 180, protein: 12, carbs: 30, fat: 2, sodium: 490, potassium: 480, category: "Meals" },
    { name: "Biryani (1 serving)", calories: 450, protein: 20, carbs: 55, fat: 15, sodium: 720, potassium: 310, category: "Meals" },
    { name: "Pizza Slice", calories: 285, protein: 12, carbs: 36, fat: 10, sodium: 640, potassium: 184, category: "Meals" },
    { name: "Burger (regular)", calories: 500, protein: 25, carbs: 40, fat: 25, sodium: 800, potassium: 350, category: "Meals" },
    { name: "Sushi Roll (6 pcs)", calories: 250, protein: 9, carbs: 37, fat: 7, sodium: 580, potassium: 170, category: "Meals" },
    { name: "Pasta Bolognese", calories: 480, protein: 22, carbs: 55, fat: 18, sodium: 650, potassium: 520, category: "Meals" },
    { name: "Fried Rice", calories: 380, protein: 10, carbs: 50, fat: 15, sodium: 820, potassium: 180, category: "Meals" },
];
export function searchFoods(query) {
    const q = query.toLowerCase();
    return FOOD_DATABASE.filter((f) => f.name.toLowerCase().includes(q) || f.category.toLowerCase().includes(q));
}
