// Gym exercise database for search + workout builder

export const gymExercises = [
  // Chest
  {
    id: 1,
    name: "Bench Press",
    muscle: "Chest",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 2,
    name: "Incline Dumbbell Press",
    muscle: "Chest",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 3,
    name: "Cable Flyes",
    muscle: "Chest",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 4,
    name: "Push-Ups",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 5,
    name: "Dumbbell Flyes",
    muscle: "Chest",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 6,
    name: "Decline Press",
    muscle: "Chest",
    equipment: "Barbell",
    type: "gym",
  },
  // Back
  {
    id: 7,
    name: "Pull-Ups",
    muscle: "Back",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 8,
    name: "Barbell Rows",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 9,
    name: "Lat Pulldowns",
    muscle: "Back",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 10,
    name: "Seated Cable Row",
    muscle: "Back",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 11,
    name: "Dumbbell Rows",
    muscle: "Back",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 12,
    name: "Inverted Rows",
    muscle: "Back",
    equipment: "Bodyweight",
    type: "home",
  },
  // Shoulders
  {
    id: 13,
    name: "Overhead Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 14,
    name: "Lateral Raises",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 15,
    name: "Face Pulls",
    muscle: "Shoulders",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 16,
    name: "Pike Push-Ups",
    muscle: "Shoulders",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 17,
    name: "Arnold Press",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },
  // Legs
  {
    id: 18,
    name: "Barbell Squats",
    muscle: "Legs",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 19,
    name: "Romanian Deadlift",
    muscle: "Legs",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 20,
    name: "Leg Press",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 21,
    name: "Lunges",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 22,
    name: "Leg Curls",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 23,
    name: "Calf Raises",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 24,
    name: "Bodyweight Squats",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 25,
    name: "Bulgarian Split Squats",
    muscle: "Legs",
    equipment: "Dumbbell",
    type: "home",
  },
  // Arms
  {
    id: 26,
    name: "Barbell Curls",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 27,
    name: "Tricep Pushdowns",
    muscle: "Arms",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 28,
    name: "Hammer Curls",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 29,
    name: "Diamond Push-Ups",
    muscle: "Arms",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 30,
    name: "Skull Crushers",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 31,
    name: "Chin-Ups",
    muscle: "Arms",
    equipment: "Bodyweight",
    type: "home",
  },
  // Core
  {
    id: 32,
    name: "Plank",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 33,
    name: "Cable Crunches",
    muscle: "Core",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 34,
    name: "Hanging Leg Raises",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "gym",
  },
  {
    id: 35,
    name: "Mountain Climbers",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 36,
    name: "Russian Twists",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 37,
    name: "Dead Bugs",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  // Full Body
  {
    id: 38,
    name: "Deadlift",
    muscle: "Full Body",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 39,
    name: "Burpees",
    muscle: "Full Body",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 40,
    name: "Clean & Press",
    muscle: "Full Body",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 41,
    name: "Kettlebell Swings",
    muscle: "Full Body",
    equipment: "Kettlebell",
  },
  // Additional Chest
  {
    id: 42,
    name: "Pec Deck Machine",
    muscle: "Chest",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 43,
    name: "Chest Press Machine",
    muscle: "Chest",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 44,
    name: "Dumbbell Pullover",
    muscle: "Chest",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 45,
    name: "Guillotine Press",
    muscle: "Chest",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 46,
    name: "Floor Press",
    muscle: "Chest",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 47,
    name: "Spiderman Push-Ups",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 48,
    name: "Plyo Push-Ups",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "home",
  },
  // Additional Back
  {
    id: 49,
    name: "T-Bar Row",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 50,
    name: "Meadows Row",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 51,
    name: "Renegade Row",
    muscle: "Back",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 52,
    name: "Straight Arm Pulldown",
    muscle: "Back",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 53,
    name: "Machine Row",
    muscle: "Back",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 54,
    name: "Good Mornings",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 55,
    name: "Superman",
    muscle: "Back",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 56,
    name: "Hyperextensions",
    muscle: "Back",
    equipment: "Machine",
    type: "gym",
  },
  // Additional Shoulders
  {
    id: 57,
    name: "Front Raises",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 58,
    name: "Upright Row",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 59,
    name: "Reverse Pec Deck",
    muscle: "Shoulders",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 60,
    name: "Cable Lateral Raises",
    muscle: "Shoulders",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 61,
    name: "Push Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 62,
    name: "Landmine Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 63,
    name: "Handstand Push-Ups",
    muscle: "Shoulders",
    equipment: "Bodyweight",
    type: "home",
  },
  // Additional Legs
  {
    id: 64,
    name: "Front Squat",
    muscle: "Legs",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 65,
    name: "Hack Squat",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 66,
    name: "Goblet Squat",
    muscle: "Legs",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 67,
    name: "Sumo Deadlift",
    muscle: "Legs",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 68,
    name: "Leg Extension",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 69,
    name: "Seated Calf Raise",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 70,
    name: "Hip Thrust",
    muscle: "Legs",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 71,
    name: "Glute Kickbacks",
    muscle: "Legs",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 72,
    name: "Pistol Squats",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 73,
    name: "Box Jumps",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  // Additional Arms
  {
    id: 74,
    name: "Preacher Curls",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 75,
    name: "Concentration Curls",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 76,
    name: "Cable Curls",
    muscle: "Arms",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 77,
    name: "Overhead Tricep Extension",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 78,
    name: "Close Grip Bench Press",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 79,
    name: "Tricep Dips",
    muscle: "Arms",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 80,
    name: "Wrist Curls",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 81,
    name: "Reverse Curls",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  // Additional Core
  {
    id: 82,
    name: "Ab Wheel Rollout",
    muscle: "Core",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 83,
    name: "Bicycle Crunches",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 84,
    name: "Leg Raises",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 85,
    name: "Flutter Kicks",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 86,
    name: "V-Ups",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 87,
    name: "Side Plank",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 88,
    name: "Toes to Bar",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "gym",
  },
  // Additional Full Body
  {
    id: 89,
    name: "Snatch",
    muscle: "Full Body",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 90,
    name: "Power Clean",
    muscle: "Full Body",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 91,
    name: "Thrusters",
    muscle: "Full Body",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 92,
    name: "Farmer's Walk",
    muscle: "Full Body",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 93,
    name: "Battle Ropes",
    muscle: "Full Body",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 94,
    name: "Sled Push",
    muscle: "Full Body",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 95,
    name: "Jumping Jacks",
    muscle: "Full Body",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 96,
    name: "Bear Crawl",
    muscle: "Full Body",
    equipment: "Bodyweight",
    type: "home",
  },

  // --- NEW EXPANDED EXERCISES ---

  // Extended Chest
  {
    id: 97,
    name: "Chest Dips",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "gym",
  },
  {
    id: 98,
    name: "Cable Crossover",
    muscle: "Chest",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 99,
    name: "Dumbbell Squeeze Press",
    muscle: "Chest",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 100,
    name: "Decline Dumbbell Press",
    muscle: "Chest",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 101,
    name: "Archer Push-Ups",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 102,
    name: "Decline Push-Ups",
    muscle: "Chest",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 103,
    name: "Banded Push-Ups",
    muscle: "Chest",
    equipment: "Band",
    type: "home",
  },

  // Extended Back
  {
    id: 104,
    name: "Pendlay Row",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 105,
    name: "Rack Pulls",
    muscle: "Back",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 106,
    name: "Chest-Supported Dumbbell Row",
    muscle: "Back",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 107,
    name: "Single-Arm Cable Row",
    muscle: "Back",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 108,
    name: "Reverse Snow Angels",
    muscle: "Back",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 109,
    name: "Towel Pull-Ups",
    muscle: "Back",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 110,
    name: "Lat Prayers (Cable)",
    muscle: "Back",
    equipment: "Cable",
    type: "gym",
  },

  // Extended Shoulders
  {
    id: 111,
    name: "Barbell Shrugs",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 112,
    name: "Dumbbell Shrugs",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 113,
    name: "Z-Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 114,
    name: "Cuban Press",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 115,
    name: "Dive Bomber Push-Ups",
    muscle: "Shoulders",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 116,
    name: "Wall Walks",
    muscle: "Shoulders",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 117,
    name: "Seated Dumbbell Press",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    type: "gym",
  },

  // Extended Legs
  {
    id: 118,
    name: "Nordic Hamstring Curls",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 119,
    name: "Step-Ups",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 120,
    name: "Dumbbell Walking Lunges",
    muscle: "Legs",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 121,
    name: "Jump Squats",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 122,
    name: "Glute Bridge",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 123,
    name: "Donkey Kicks",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 124,
    name: "Fire Hydrants",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 125,
    name: "Lying Leg Curls",
    muscle: "Legs",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 126,
    name: "Sissy Squats",
    muscle: "Legs",
    equipment: "Bodyweight",
    type: "home",
  },

  // Extended Arms
  {
    id: 127,
    name: "Zottman Curls",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 128,
    name: "Spider Curls",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 129,
    name: "Drag Curls",
    muscle: "Arms",
    equipment: "Barbell",
    type: "gym",
  },
  {
    id: 130,
    name: "Dumbbell Kickbacks",
    muscle: "Arms",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 131,
    name: "Cable Kickbacks",
    muscle: "Arms",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 132,
    name: "Bench Dips",
    muscle: "Arms",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 133,
    name: "Machine Bicep Curls",
    muscle: "Arms",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 134,
    name: "Machine Tricep Extensions",
    muscle: "Arms",
    equipment: "Machine",
    type: "gym",
  },
  {
    id: 135,
    name: "Rope Tricep Pushdowns",
    muscle: "Arms",
    equipment: "Cable",
    type: "gym",
  },

  // Extended Core
  {
    id: 136,
    name: "Dragon Flags",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "gym",
  },
  {
    id: 137,
    name: "Hollow Body Hold",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 138,
    name: "Cable Woodchoppers",
    muscle: "Core",
    equipment: "Cable",
    type: "gym",
  },
  {
    id: 139,
    name: "Plank Jacks",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 140,
    name: "Bird Dog",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 141,
    name: "Sit-Ups",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 142,
    name: "Heel Touches",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 143,
    name: "L-Sit",
    muscle: "Core",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 144,
    name: "Decline Crunches",
    muscle: "Core",
    equipment: "Bench",
    type: "gym",
  },

  // Extended Full Body
  {
    id: 145,
    name: "Turkish Get-Up",
    muscle: "Full Body",
    equipment: "Kettlebell",
    type: "gym",
  },
  {
    id: 146,
    name: "Dumbbell Snatch",
    muscle: "Full Body",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 147,
    name: "Devil's Press",
    muscle: "Full Body",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 148,
    name: "Man Makers",
    muscle: "Full Body",
    equipment: "Dumbbell",
    type: "gym",
  },
  {
    id: 149,
    name: "Broad Jumps",
    muscle: "Full Body",
    equipment: "Bodyweight",
    type: "home",
  },
  {
    id: 150,
    name: "Wall Balls",
    muscle: "Full Body",
    equipment: "Medicine Ball",
    type: "gym",
  },
  {
    id: 151,
    name: "Medicine Ball Slams",
    muscle: "Full Body",
    equipment: "Medicine Ball",
    type: "gym",
  },
];

// Cardio types with MET values
export const cardioTypes = [
  { id: "treadmill", label: "Treadmill", icon: "🏃", met: 8.0 },
  { id: "cycling", label: "Cycling", icon: "🚴", met: 7.5 },
  { id: "stairmaster", label: "Stairmaster", icon: "🧗", met: 9.0 },
  { id: "rowing", label: "Rowing", icon: "🚣", met: 7.0 },
  { id: "elliptical", label: "Elliptical", icon: "🚶", met: 5.0 },
  { id: "swimming", label: "Swimming", icon: "🏊", met: 8.0 },
  { id: "jogging", label: "Jogging", icon: "🧍", met: 7.0 },
  { id: "walking", label: "Walking", icon: "🚶", met: 3.5 },
];

// Estimate calories: MET * weight_kg * duration_hours
export function estimateCalories(met, weightKg, durationMinutes) {
  const weight = weightKg || 70;
  return Math.round(met * weight * (durationMinutes / 60));
}

// AI workout plan templates
export const aiWorkoutTemplates = {
  strength: {
    monday: [
      { name: "Bench Press", sets: 4, reps: 8 },
      { name: "Incline Dumbbell Press", sets: 3, reps: 10 },
      { name: "Cable Flyes", sets: 3, reps: 12 },
      { name: "Tricep Pushdowns", sets: 3, reps: 12 },
    ],
    tuesday: [
      { name: "Barbell Squats", sets: 4, reps: 8 },
      { name: "Romanian Deadlift", sets: 3, reps: 10 },
      { name: "Leg Press", sets: 3, reps: 12 },
      { name: "Calf Raises", sets: 4, reps: 15 },
    ],
    wednesday: [],
    thursday: [
      { name: "Pull-Ups", sets: 4, reps: 8 },
      { name: "Barbell Rows", sets: 4, reps: 8 },
      { name: "Face Pulls", sets: 3, reps: 15 },
      { name: "Barbell Curls", sets: 3, reps: 12 },
    ],
    friday: [
      { name: "Overhead Press", sets: 4, reps: 8 },
      { name: "Lateral Raises", sets: 3, reps: 12 },
      { name: "Arnold Press", sets: 3, reps: 10 },
      { name: "Plank", sets: 3, reps: 60 },
    ],
    saturday: [
      { name: "Deadlift", sets: 4, reps: 5 },
      { name: "Bulgarian Split Squats", sets: 3, reps: 10 },
      { name: "Hanging Leg Raises", sets: 3, reps: 12 },
      { name: "Russian Twists", sets: 3, reps: 20 },
    ],
    sunday: [],
  },
  lose: {
    monday: [
      { name: "Burpees", sets: 4, reps: 15 },
      { name: "Mountain Climbers", sets: 3, reps: 30 },
      { name: "Bodyweight Squats", sets: 3, reps: 20 },
      { name: "Push-Ups", sets: 3, reps: 15 },
    ],
    tuesday: [],
    wednesday: [
      { name: "Lunges", sets: 3, reps: 12 },
      { name: "Plank", sets: 3, reps: 45 },
      { name: "Diamond Push-Ups", sets: 3, reps: 12 },
      { name: "Kettlebell Swings", sets: 4, reps: 15 },
    ],
    thursday: [],
    friday: [
      { name: "Pull-Ups", sets: 3, reps: 8 },
      { name: "Barbell Squats", sets: 4, reps: 10 },
      { name: "Dead Bugs", sets: 3, reps: 12 },
      { name: "Russian Twists", sets: 3, reps: 20 },
    ],
    saturday: [
      { name: "Burpees", sets: 3, reps: 12 },
      { name: "Mountain Climbers", sets: 3, reps: 30 },
      { name: "Bodyweight Squats", sets: 4, reps: 20 },
    ],
    sunday: [],
  },
};

export const DAYS_OF_WEEK = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

export const DAY_LABELS = {
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  thursday: "Thu",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun",
};
