const homeWorkouts = [
  {
    name: "Full Body Burn",
    type: "home",
    duration: "25 min",
    exercises: [
      {
        name: "Jumping Jacks",
        duration: "60s",
        description: "Full body warm-up cardio",
      },
      {
        name: "Push-ups",
        reps: "3x12",
        duration: "4 min",
        description: "Chest, shoulders, triceps",
      },
      {
        name: "Bodyweight Squats",
        reps: "3x15",
        duration: "4 min",
        description: "Quads, glutes, hamstrings",
      },
      { name: "Plank", duration: "3x45s", description: "Core stability" },
      {
        name: "Lunges",
        reps: "3x10 each",
        duration: "5 min",
        description: "Legs and balance",
      },
      {
        name: "Burpees",
        reps: "3x8",
        duration: "4 min",
        description: "Full body explosive",
      },
      {
        name: "Mountain Climbers",
        duration: "3x30s",
        description: "Core and cardio",
      },
    ],
  },
  {
    name: "Core Crusher",
    type: "home",
    duration: "20 min",
    exercises: [
      {
        name: "Bicycle Crunches",
        reps: "3x20",
        duration: "4 min",
        description: "Obliques and abs",
      },
      {
        name: "Leg Raises",
        reps: "3x12",
        duration: "3 min",
        description: "Lower abs",
      },
      {
        name: "Russian Twists",
        reps: "3x20",
        duration: "4 min",
        description: "Obliques",
      },
      { name: "Plank", duration: "3x60s", description: "Full core engagement" },
      {
        name: "Dead Bug",
        reps: "3x10 each",
        duration: "4 min",
        description: "Core stability",
      },
      {
        name: "Flutter Kicks",
        duration: "3x30s",
        description: "Lower abs and hip flexors",
      },
    ],
  },
  {
    name: "HIIT Cardio",
    type: "home",
    duration: "20 min",
    exercises: [
      {
        name: "High Knees",
        duration: "45s on/15s off x4",
        description: "Cardio burst",
      },
      {
        name: "Squat Jumps",
        reps: "3x10",
        duration: "3 min",
        description: "Explosive legs",
      },
      {
        name: "Burpees",
        reps: "3x8",
        duration: "4 min",
        description: "Full body",
      },
      {
        name: "Tuck Jumps",
        reps: "3x8",
        duration: "3 min",
        description: "Plyometric power",
      },
      {
        name: "Speed Skaters",
        duration: "3x30s",
        description: "Lateral cardio",
      },
    ],
  },
];
const gymWorkouts = [
  {
    name: "Push Day",
    type: "gym",
    duration: "45 min",
    exercises: [
      {
        name: "Bench Press",
        reps: "4x8",
        duration: "8 min",
        description: "Main chest compound",
      },
      {
        name: "Overhead Press",
        reps: "3x10",
        duration: "6 min",
        description: "Shoulders",
      },
      {
        name: "Incline Dumbbell Press",
        reps: "3x10",
        duration: "6 min",
        description: "Upper chest",
      },
      {
        name: "Lateral Raises",
        reps: "3x12",
        duration: "5 min",
        description: "Side delts",
      },
      {
        name: "Tricep Pushdowns",
        reps: "3x12",
        duration: "5 min",
        description: "Triceps isolation",
      },
      {
        name: "Dips",
        reps: "3x10",
        duration: "5 min",
        description: "Chest and triceps",
      },
    ],
  },
  {
    name: "Pull Day",
    type: "gym",
    duration: "45 min",
    exercises: [
      {
        name: "Deadlifts",
        reps: "4x6",
        duration: "10 min",
        description: "Full posterior chain",
      },
      {
        name: "Pull-ups",
        reps: "3x8",
        duration: "6 min",
        description: "Back and biceps",
      },
      {
        name: "Barbell Rows",
        reps: "3x10",
        duration: "6 min",
        description: "Back thickness",
      },
      {
        name: "Face Pulls",
        reps: "3x15",
        duration: "5 min",
        description: "Rear delts, posture",
      },
      {
        name: "Barbell Curls",
        reps: "3x10",
        duration: "5 min",
        description: "Biceps",
      },
      {
        name: "Hammer Curls",
        reps: "3x10",
        duration: "5 min",
        description: "Brachialis",
      },
    ],
  },
  {
    name: "Leg Day",
    type: "gym",
    duration: "50 min",
    exercises: [
      {
        name: "Barbell Squats",
        reps: "4x8",
        duration: "10 min",
        description: "King of leg exercises",
      },
      {
        name: "Romanian Deadlifts",
        reps: "3x10",
        duration: "7 min",
        description: "Hamstrings and glutes",
      },
      {
        name: "Leg Press",
        reps: "3x12",
        duration: "6 min",
        description: "Quad focus",
      },
      {
        name: "Walking Lunges",
        reps: "3x10 each",
        duration: "6 min",
        description: "Unilateral strength",
      },
      {
        name: "Leg Curls",
        reps: "3x12",
        duration: "5 min",
        description: "Hamstring isolation",
      },
      {
        name: "Calf Raises",
        reps: "4x15",
        duration: "5 min",
        description: "Calf development",
      },
    ],
  },
];
export function getWorkoutPlans(type) {
  return type === "home" ? homeWorkouts : gymWorkouts;
}
export const faceExercises = [
  {
    name: "Jawline Clenches",
    duration: "3x15 reps",
    icon: "💪",
    description: "Clench jaw tightly, hold 5s, release. Defines jawline.",
    target: "Masseter, Jawline",
    timerSeconds: 75,
    steps: [
      "Sit upright with your mouth slightly open",
      "Clench your jaw tightly for 5 seconds",
      "Release slowly and rest for 2 seconds",
      "Repeat 15 times for 3 sets",
    ],
  },
  {
    name: "Cheek Puffs",
    duration: "3x10 reps",
    icon: "🐡",
    description: "Puff air into each cheek alternately. Tones cheek muscles.",
    target: "Buccinator, Cheeks",
    timerSeconds: 60,
    steps: [
      "Close your mouth and puff your right cheek with air",
      "Hold for 5 seconds, then shift air to left cheek",
      "Hold for 5 seconds on the left side",
      "Repeat alternating 10 times per set, 3 sets",
    ],
  },
  {
    name: "Fish Face",
    duration: "3x15s hold",
    icon: "🐟",
    description: "Suck cheeks in, hold, then smile. Tones cheeks and lips.",
    target: "Cheeks, Lip Muscles",
    timerSeconds: 45,
    steps: [
      "Suck your cheeks in as far as possible",
      "While holding, try to smile",
      "Hold this position for 15 seconds",
      "Relax and repeat 3 times",
    ],
  },
  {
    name: "Neck Tilts",
    duration: "3x10 each side",
    icon: "🦒",
    description: "Tilt head side to side slowly. Reduces neck tension.",
    target: "Sternocleidomastoid, Neck",
    timerSeconds: 60,
    steps: [
      "Sit or stand with shoulders relaxed",
      "Slowly tilt your head toward your right shoulder",
      "Hold for 3 seconds, feeling the stretch",
      "Return to center, then tilt to the left",
      "Repeat 10 times per side for 3 sets",
    ],
  },
  {
    name: "Chin Lifts",
    duration: "3x15 reps",
    icon: "👆",
    description: "Look up, push jaw forward, hold 3s. Reduces double chin.",
    target: "Platysma, Submental",
    timerSeconds: 75,
    steps: [
      "Tilt your head back to look at the ceiling",
      "Push your lower jaw forward until you feel a stretch",
      "Hold for 3 seconds",
      "Relax and lower your head back to neutral",
      "Repeat 15 times for 3 sets",
    ],
  },
  {
    name: "Eye Squeeze",
    duration: "3x15 reps",
    icon: "👁️",
    description:
      "Squeeze eyes shut tightly, hold 3s, release. Reduces crow's feet.",
    target: "Orbicularis Oculi",
    timerSeconds: 75,
    steps: [
      "Close your eyes normally",
      "Squeeze them tightly shut for 3 seconds",
      "Open wide for 1 second",
      "Repeat squeezing 15 times per set, 3 sets",
    ],
  },
  {
    name: "Forehead Smoother",
    duration: "3x10 reps",
    icon: "🤚",
    description: "Place fingers on forehead, raise brows against resistance.",
    target: "Frontalis, Forehead",
    timerSeconds: 60,
    steps: [
      "Place both hands flat on your forehead",
      "Apply gentle downward pressure with your fingers",
      "Try to raise your eyebrows against the resistance",
      "Hold for 3 seconds, then relax",
      "Repeat 10 times for 3 sets",
    ],
  },
  {
    name: "Neck Rotations",
    duration: "2x5 each direction",
    icon: "🔄",
    description: "Slowly rotate head in circles. Relieves tension.",
    target: "Trapezius, Neck",
    timerSeconds: 40,
    steps: [
      "Drop your chin to your chest",
      "Slowly roll your head to the right shoulder",
      "Continue rolling back, then to the left shoulder",
      "Complete the circle back to the chest",
      "Do 5 rotations clockwise, then 5 counter-clockwise, 2 sets",
    ],
  },
  {
    name: "Tongue Press",
    duration: "3x10s hold",
    icon: "👅",
    description: "Press tongue to roof of mouth. Defines jawline underneath.",
    target: "Mylohyoid, Submental",
    timerSeconds: 30,
    steps: [
      "Close your mouth with teeth together",
      "Press the flat of your tongue firmly against the roof of your mouth",
      "Hold for 10 seconds while maintaining pressure",
      "Relax and repeat 3 times",
    ],
  },
  {
    name: "Smile & Hold",
    duration: "3x10s",
    icon: "😊",
    description: "Wide smile, hold 10 seconds. Lifts cheeks naturally.",
    target: "Zygomaticus, Cheeks",
    timerSeconds: 30,
    steps: [
      "Smile as wide as you naturally can",
      "Hold the maximum smile for 10 seconds",
      "Relax your face completely for 5 seconds",
      "Repeat 3 times",
    ],
  },
];
export const skincareRoutine = [
  {
    step: 1,
    name: "Cleanser",
    description: "Gentle face wash to remove dirt and oil",
    when: "both",
    tip: "Use lukewarm water, not hot",
  },
  {
    step: 2,
    name: "Toner",
    description: "Balance skin pH and prep for products",
    when: "both",
    tip: "Pat gently, don't rub",
  },
  {
    step: 3,
    name: "Vitamin C Serum",
    description: "Brightens skin and fights free radicals",
    when: "morning",
    tip: "Apply before moisturizer",
  },
  {
    step: 4,
    name: "Retinol / Retinoid",
    description: "Anti-aging, reduces acne and dark spots",
    when: "evening",
    tip: "Start 2x/week, build tolerance",
  },
  {
    step: 5,
    name: "Moisturizer",
    description: "Hydrate and lock in previous products",
    when: "both",
    tip: "Apply while skin is still slightly damp",
  },
  {
    step: 6,
    name: "Sunscreen SPF 30+",
    description: "Protect from UV damage and aging",
    when: "morning",
    tip: "Reapply every 2 hours if outdoors",
  },
  {
    step: 7,
    name: "Eye Cream",
    description: "Hydrate under-eye area, reduce dark circles",
    when: "both",
    tip: "Use ring finger, lightest pressure",
  },
  {
    step: 8,
    name: "Lip Balm with SPF",
    description: "Protect and moisturize lips",
    when: "morning",
    tip: "Reapply throughout the day",
  },
];
